services:
    mysql:
        image: 'mysql:8.4'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-root}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE:-testing}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'numerosis-mysql:/var/lib/mysql'
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-proot']
            retries: 3
            timeout: 5s

    pgsql:
        image: 'postgres:17'
        ports:
            - '${FORWARD_PGSQL_PORT:-5432}:5432'
        environment:
            POSTGRES_USER: '${PGSQL_USERNAME:-postgres}'
            POSTGRES_PASSWORD: '${PGSQL_PASSWORD:-postgres}'
            POSTGRES_DB: '${PGSQL_DATABASE:-testing}'
        volumes:
            - 'numerosis-pgsql:/var/lib/postgresql/data'
        healthcheck:
            test: ['CMD', 'pg_isready', '-U', 'postgres']
            retries: 3
            timeout: 5s

volumes:
    numerosis-mysql:
        driver: local
    numerosis-pgsql:
        driver: local
